In [3]:
import numpy as np

np.array([1,2,3])


array([1, 2, 3])

In [4]:
d2=[[1,2,3],[4,5,6],[7,8,9]]
np.array(d2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(5,5)

array([[0.83247243, 0.19491771, 0.26895932, 0.04872063, 0.69672123],
       [0.15691894, 0.84018553, 0.5751904 , 0.37179319, 0.58149906],
       [0.78816447, 0.04395945, 0.84275689, 0.02760034, 0.73520351],
       [0.19384028, 0.01269225, 0.53561548, 0.87016438, 0.94595106],
       [0.96131704, 0.82245669, 0.77564941, 0.11117049, 0.84671582]])

In [11]:
np.random.randn(2,2)

array([[ 0.93675398, -1.12064446],
       [ 0.04968121,  0.40031827]])

In [12]:
np.random.randint(1,100,10)

array([83, 27, 47,  9,  3, 14, 50, 38, 12, 52])

In [13]:
arr=np.arange(40,65)
arr

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64])

In [14]:
arr.reshape(5,5)

array([[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64]])

In [15]:
print(arr.max())
print(arr.min())

64
40


In [16]:
print(arr.argmin())
print(arr.argmax())


0
24


In [17]:
arr.shape

(25,)

In [20]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr[5:]=100
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100])

In [30]:
arr2d=np.arange(5,46,5).reshape(3,3)
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr2d[1,2]

30

In [34]:
arr2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
arr2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [37]:
arr[5:]=np.arange(5,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
boolArr=arr>5
arr[boolArr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr<4]

array([0, 1, 2, 3])

In [46]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [47]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [55]:
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [57]:
(arr+100)/100


array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ])

In [58]:
arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [59]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [60]:
np.max(arr)

10

In [61]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [62]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [65]:
np.zeros(10)+1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
np.arange(0,1.01,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [72]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [74]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [76]:
mat[4]

array([21, 22, 23, 24, 25])

In [87]:
np.sqrt(np.sum((mat-np.sum(mat)/len(mat)**2)**2)/len(mat)**2)

7.211102550927978

In [89]:
np.std(mat)

7.211102550927978

In [98]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])